name: CI_Android

on:
  push:
    branches:
    - master
    - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Run test suite"
      uses: msfjarvis/setup-android@1.0
      run: 
      with:
        entrypoint: ls
        args: 
