name: CI_Android

on:
  push:
    branches:
    - master
    - release/*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Run LS Command"
      working-directory: ./
      run: ls -la

    - name: "Run Build Android"
      uses: msfjarvis/setup-android@1.0
      with:
        entrypoint: ./gradlew
        args: assembleDebug
